options:
  dcf_path: "@BUS_CONFIG_PATH@"

master:
  node_id: 127
  driver: "ros2_canopen::MasterDriver"
  package: "canopen_master_driver"
  baud_rate: 500
  heartbeat_consumer: true
  heartbeat_producer: 1000
  sync_period: 100000 # 100ms

defaults:
  heartbeat_consumer: true
  heartbeat_producer: 1000
  
nodes:
  packaging_machine_1:
    node_id: 32
    vendor_id: 0x1234
    product_code: 0x1234
    revision_number: 0
    polling: true
    dcf: "DS301_profile.eds"
    driver: "ros2_canopen::ProxyDriver" # "ros2_canopen::LifecycleProxyDriver"
    package: "canopen_proxy_driver"
    period: 100
    enable_lazy_load: true
    # sdo:
    #   - {index: 0x6040, sub_index: 0, value: 0x86} # Controlword, clear error
    #   - {index: 0x6040, sub_index: 0, value: 0x6} # Controlword, clear error
    #   - {index: 0x607A, sub_index: 0, value: 0x0} # Target position
    #   - {index: 0x6081, sub_index: 0, value: 0x0} # Profile velocity
    #   - {index: 0x60FF, sub_index: 0, value: 0x0} # Target velocity
    #   - {index: 0x60C2, sub_index: 1, value: 50} # Set interpolation time for cyclic modes to 50 ms
    #   - {index: 0x60C2, sub_index: 2, value: -3} # Set base 10-3s
    # tpdo:
    #   1:
    #     enabled: true
    #     cob_id: "auto"
    #     transmission: 0x1
    #     mapping:
    #       - {index: 0x6040, sub_index: 0} # Controlword 
    #       - {index: 0x6060, sub_index: 0} # Operation Mode
    #       - {index: 0x6041, sub_index: 0} # Statusword 
    #       - {index: 0x6078, sub_index: 0} # Actual Current
    #   2:
    #     enabled: true
    #     cob_id: "auto"
    #     transmission: 0x1
    #     mapping:
    #       - {index: 0x6063, sub_index: 0} # Actual Position
    #       - {index: 0x606C, sub_index: 0} # Actual Rotate Speed
    #   3:
    #     enabled: true
    #     cob_id: "auto"
    #     transmission: 0x1
    #     mapping:
    #     - {index: 0x2680, sub_index: 0} # Warning word
    #     # - {index: 0x6410, sub_index: 19} # Motor Temperature # Error!!!
    # rpdo:
    #   1:
    #     enabled: true
    #     cob_id: "auto"
    #     mapping:
    #     - {index: 0x6040, sub_index: 0} # Controlword
    #     - {index: 0x6060, sub_index: 0} # Operation Mode
    #     - {index: 0x60FF, sub_index: 0} # Target velocity
    #   2:
    #     enabled: true
    #     cob_id: "auto"
    #     mapping:
    #     - {index: 0x607A, sub_index: 0} # Target position
    #     - {index: 0x6081, sub_index: 0} # Profile velocity
    #   3:
    #     enabled: true
    #     cob_id: "auto"
    #     mapping:
    #     - {index: 0x6083, sub_index: 0} # Profile acc
    #     - {index: 0x6084, sub_index: 0} # Profile dec

      


